mashcard/mashcard

.github/workflows/stale.yml

Signed-off-by: Li (Boris) Ding <ding@brickdoc.com>

ci: add stale action

---

apps/server-monolith/config/locales/pwa.en-US.yml
packages/brickdoc-editor/src/components/editorViews/HistoryList/HistoryList.tsx
packages/brickdoc-editor/src/components/editorViews/HistoryList/HistoryListMenu.tsx
packages/brickdoc-editor/src/components/editorViews/HistoryList/__tests__/HistoryListMenu.test.tsx
packages/brickdoc-editor/src/components/editorViews/HistoryList/index.ts

- add missing formats back for history time
- separate HistoryListMenu and jest

fix(history): add missing formats back for history time

---

packages/brickdoc-editor/src/components/editorViews/Discussion/useCommentedNodes.ts

makes commentedNodes stable during editor updation.

fix(editor): fix conversation fetcher trigger too frequently

---

packages/brickdoc-uploader/package.json
tools/e2e-testing/package.json
yarn.lock

This is an auto-created PR to upgrade our dependencies according to <https://github.com/brickdoc/brickdoc/blob/master/.github/workflows/dependency_updater.yml>.

build(deps): upgrade dependencies

---

packages/brickdoc-editor/__snapshots__/components/editorViews/Discussion/__tests__/DiscussionPanel/DiscussionPanel.test.tsx.snap
packages/brickdoc-editor/__snapshots__/components/ui/Drawer/__tests__/Drawer.test.tsx.snap
packages/brickdoc-editor/src/components/editorViews/Discussion/DiscussionList/DiscussionList.style.ts
packages/brickdoc-editor/src/components/editorViews/Discussion/DiscussionPanel/DiscussionPanel.style.ts
packages/brickdoc-editor/src/components/editorViews/Discussion/useCommentedNodes.ts
packages/brickdoc-editor/src/components/ui/Drawer/Drawer.tsx
packages/brickdoc-editor/src/extensions/marks/discussion/discussion.ts
packages/brickdoc-editor/src/helpers/discussion.ts

* makes conversation active when anchor focuses on a discussion mark.
* shows conversation correctly when it is locked in an active state.

fix(editor): fixes conversation focused style

---

packages/brickdoc-editor/src/components/blockViews/HeadingView/HeadingView.tsx
packages/brickdoc-editor/src/extensions/blocks/heading/heading.ts

fix(editor): aligns block actions menu to heading text

---

packages/brickdoc-editor/__snapshots__/components/blockViews/CalloutView/__tests__/CalloutView.test.tsx.snap
packages/brickdoc-editor/__snapshots__/components/blockViews/TocView/__tests__/TocView.test.tsx.snap
packages/brickdoc-editor/__snapshots__/extensions/blocks/callout/__tests__/callout.test.tsx.snap
packages/brickdoc-editor/src/components/blockViews/CalloutView/CalloutView.tsx
packages/brickdoc-editor/src/components/blockViews/TocView/TocNodePanel.tsx
packages/brickdoc-editor/src/components/blockViews/TocView/TocView.tsx

1. adds max-width to callout node
2. adds max-width to toc node
3. adds debounce to calculate toc content

Fix toc node and callout node styles

---

README.md
apps/server-monolith/app/graphql/types/blocks/cover.rb
packages/uploader/__snapshots__/Dashboard/__tests__/Dashboard.test.tsx.snap
packages/uploader/src/Dashboard/index.style.ts

Fix #39
https://user-images.githubusercontent.com/5107241/175101944-0fe8776b-d9b9-4113-990b-294c57ff9b56.mov

fix: add a mask background when hover on the unsplash image cards

---

apps/client-web/src/docs/common/components/CollaboratorsMenu/index.style.ts
apps/client-web/src/docs/pages/components/DocumentTitle/DocumentTitle.tsx
apps/client-web/src/docs/pages/components/DocumentTopBar/DocumentTopBar.tsx
apps/client-web/src/docs/pages/hooks/useBlockSyncProvider.ts
apps/server-monolith/app/models/mashcard_config.rb

- cleanup experiment flags
- change margin of topbar collaborators [#81](https://github.com/mashcard/mashcard/issues/81)

feat(document): cleanup experiment flags

---

apps/client-web/global.d.ts
apps/client-web/src/docs/pages/DocumentContentPage.tsx
apps/client-web/src/docs/pages/Trash.tsx
apps/client-web/src/docs/store/DocMeta/DocMetaProvider.tsx
apps/client-web/src/docs/store/DocMeta/types.ts
apps/server-monolith/app/helpers/application_helper.rb
apps/server-monolith/lib/mashcard/runtime.rb

Fix #33
Domain name is already passed in env var `HOST` but not used in server code. This PR fix that.

fix: fix incorrect host in container environment

---

apps/server-monolith/app/controllers/accounts/omniauth_callbacks_controller.rb

fix: `undefined method user` error

fix: omniauth redirect

---

packages/editor/__snapshots__/editors/documentEditor/__tests__/documentEditor.test.tsx.snap
packages/editor/src/editors/documentEditor/documentEditor.style.ts
packages/editor/src/editors/documentEditor/documentEditor.tsx

show selection when editor is not editable

fix(editor): show selection when editor is not editable

---

packages/editor/src/extensions/extensions/selection/selection.ts

Assume there are serval continuous non-text nodes in the editor. When we select the first node, `window Selection` will jump over all these non-text nodes and focus on the nearest text node. When `Prosemirror` creates the `TextSelection`, it will look for `window.getSelection()` and get the `focusNode` of `Selection` which is the nearest text node but not the first non-text node. That causes Prosemirror to include all continuous non-text nodes in the TextSelection which is not what we expect.
To fix that, we need to customize TextSelection creation by excluding all continuous non-text nodes and empty text nodes at the end of the selection.
https://github.com/ProseMirror/prosemirror-view/blob/master/src/index.ts#L425-L428
https://github.com/ProseMirror/prosemirror-view/blob/master/src/selec …

fix(editor): excludes the last non-text node in the TextSelection

---

packages/editor/src/extensions/extensions/slashCommands/slashCommands.tsx

fix #51
slash menu only can be triggered by typing slash char. Avoid trigger slash menu by selection update or other events.

fix(editor): only type slash can active slash menu

---

packages/editor/src/components/extensionViews/BubbleMenu/__tests__/BubbleMenu.test.tsx
packages/editor/src/extensions/extensions/bubbleMenu/bubbleMenuViewPlugin.ts
packages/editor/src/extensions/extensions/selection/MultipleNodeSelection.ts

fix(editor): shows bubble menu in correct position according to selection

---

packages/editor/__snapshots__/components/ui/Formula/AutocompleteList/__tests__/AutocompleteList.test.tsx.snap
packages/editor/__snapshots__/components/ui/Formula/Render/__tests__/FormulaSpreadsheet.test.tsx.snap
packages/editor/__snapshots__/editors/documentEditor/__tests__/documentEditor.test.tsx.snap
packages/editor/src/components/blockViews/FormulaView/FormulaBlock.tsx
packages/editor/src/components/blockViews/FormulaView/FormulaMenu.tsx
packages/editor/src/components/blockViews/Spreadsheet/Spreadsheet.style.ts
packages/editor/src/components/blockViews/Spreadsheet/SpreadsheetCell.tsx
packages/editor/src/components/blockViews/Spreadsheet/SpreadsheetRender.tsx
packages/editor/src/components/blockViews/Spreadsheet/useFormulaSpreadsheet.ts
packages/editor/src/components/ui/Formula/Preview/ColumnPreview.tsx
packages/editor/src/components/ui/Formula/Preview/FunctionPreview.tsx
packages/editor/src/components/ui/Formula/Preview/SpreadsheetPreview.tsx
packages/formula/src/__tests__/persist.test.ts
packages/formula/src/context/context.ts
packages/formula/src/controls/cell.ts
packages/formula/src/controls/spreadsheet.ts
packages/formula/src/controls/types.ts
packages/formula/src/functions/spreadsheet/spreadsheet.ts
packages/formula/src/tests/feature/event/columnEvent.ts
packages/formula/src/tests/feature/event/rowEvent.ts
packages/formula/src/tests/feature/event/variableEvent.ts
packages/formula/src/tests/testHelper.ts
packages/formula/src/tests/testType.ts
packages/formula/src/types/index.ts

1. hide popover when menu is visible
2. fix spreadsheet preview style
3. refactor: lazy fetch `displayData`

fix(formula): spreadsheet preview style

---

apps/client-web/src/docs/common/components/PodSelect/index.styles.ts
apps/client-web/src/docs/pages/DocumentContentPage.style.ts
apps/client-web/src/settings/common/sidebar/index.ts
packages/design-system/__snapshots__/components/Tree/__tests__/stories.test.tsx.snap
packages/design-system/src/components/Tree/style/base.style.ts

Select and hover states use a cleaner through-bar design

feat(desgin): new select sidebar style

---

apps/server-monolith/app/controllers/concerns/current_pod.rb

(https://github.com/mashcard/mashcard/issues/168)

fix(pod): temp fix current_pod cannot be set correctly while switching pod

---

.github/workflows/e2e_test.yml

collection allure results by artifact.

ci: update e2e ci to send reports only once

---

packages/editor/src/extensions/extensions/collaboration/collaboration.ts
packages/editor/src/extensions/extensions/collaboration/index.ts

fix(undo): fix prosemirror undo

---

packages/editor/__snapshots__/components/blockViews/FormulaView/__tests__/formulaType.test.tsx.snap
packages/editor/__snapshots__/components/ui/Formula/AutocompleteList/__tests__/AutocompleteList.test.tsx.snap
packages/editor/src/components/blockViews/FormulaView/FormulaMenu.tsx
packages/editor/src/components/blockViews/FormulaView/useFormula.ts
packages/editor/src/components/ui/Formula/AutocompleteList/style.ts
packages/editor/src/editors/formulaEditor/FormulaEditor.tsx
packages/editor/src/extensions/extensions/formulaKeyDown/handleKeyDown.ts
packages/formula/src/__tests__/errorParse.test.ts
packages/formula/src/__tests__/successExecute.test.ts
packages/formula/src/functions/convert/toArray.ts
packages/formula/src/grammar/core.ts
packages/formula/src/grammar/operations/expression.ts
packages/formula/src/grammar/operations/parenthesis.ts
packages/formula/src/grammar/steps/addSpace.ts
packages/formula/src/tests/feature/complete/blockComplete.ts
packages/formula/src/tests/feature/other.ts
packages/formula/src/tests/testType.ts
packages/formula/src/types/index.ts

1. feat: blur as save
2. fix parse bug
3. fix expression type

feat(formula): popover menu blur as save

---

apps/client-web/src/docs/pages/DocumentPage.tsx
apps/client-web/src/docs/pages/hooks/useBlockSyncProvider.ts
apps/client-web/src/docs/pages/hooks/useEditorOptions/useEditorOptions.tsx
apps/client-web/src/docs/pages/hooks/useSyncProvider.ts
packages/editor/src/editors/documentEditor/__tests__/documentEditor.test.tsx
packages/editor/src/editors/documentEditor/documentEditor.tsx
packages/editor/src/extensions/base.ts

fix(editor): remove SyncPlugin, fix cursor glitch when saving

---

apps/client-web/src/docs/pages/hooks/useBlockSyncProvider.ts

fix(document): temp fix document block apollo cache updating

---

packages/editor/__snapshots__/components/ui/Formula/AutocompleteList/__tests__/AutocompleteList.test.tsx.snap
packages/editor/src/components/blockViews/FormulaView/FormulaBlock.tsx
packages/editor/src/components/blockViews/FormulaView/useFormula.ts
packages/editor/src/components/blockViews/Spreadsheet/SpreadsheetCell.tsx
packages/editor/src/components/ui/Formula/AutocompleteList/style.ts
packages/editor/src/components/ui/Formula/FormulaDisplay.tsx
packages/editor/src/components/ui/Formula/FormulaResult.tsx
packages/editor/src/components/ui/Formula/FormulaValue.tsx
packages/editor/src/components/ui/Formula/Preview/VariablePreview.tsx
packages/editor/src/components/ui/Formula/__tests__/FormulaDisplay.test.tsx
packages/editor/src/components/ui/Formula/__tests__/FormulaValue.test.tsx
packages/editor/src/extensions/blocks/formula/formula.ts
packages/editor/src/extensions/blocks/formula/meta.ts
packages/editor/src/extensions/marks/formulaType/formulaType.ts
packages/formula/src/context/persist.ts
packages/formula/src/types/index.ts

* ref #206
Persist some needful formula fields in block to ensure copy and paste feature is work.
*NOTE that this PR is first step, and the referenced issue is not completed yet.*

feat(formula): basic copy / cut / paste support

---

packages/editor/src/extensions/extensions/selection/domEvents.ts

fix(editor): fix the document will always be focused when click inside

---

.github/workflows/linting.yml
apps/client-web/src/docs/pages/DocumentContentPage.tsx
apps/client-web/src/docs/pages/hooks/useBlockSyncProvider.ts
packages/editor/externals.d.ts

- fix #247, when open a link with history id, history list should be opened
- fix #247, switching history version should not to change title on pagetree and breadcrumb

fix(history): fix #247

---

apps/client-web/src/docs_legacy/common/components/TrashTable/TrashList.tsx
apps/server-monolith/config/locales/pwa.en-US.yml
apps/server-monolith/config/locales/pwa.ja-JP.yml
apps/server-monolith/config/locales/pwa.zh-TW.yml
packages/design-system/src/components/Menu/menu.tsx
packages/design-system/src/components/Popover/styles/index.style.ts
packages/design-system/src/themes/ceramic-light/colors/ceramics.ts
packages/editor/__snapshots__/components/blockViews/BlockActions/__tests__/BlockActionsMenu.test.tsx.snap
packages/editor/__snapshots__/components/extensionViews/MentionMenu/__tests__/MentionMenu.test.tsx.snap
packages/editor/__snapshots__/components/extensionViews/MentionMenu/__tests__/PageGroup.test.tsx.snap
packages/editor/__snapshots__/components/extensionViews/MentionMenu/__tests__/UserGroup.test.tsx.snap
packages/editor/__snapshots__/components/extensionViews/SlashMenu/__tests__/SlashMenu.test.tsx.snap
packages/editor/src/components/extensionViews/BubbleMenu/useBubbleMenuItems/useFontColorGroup.tsx
packages/editor/src/components/extensionViews/SlashMenu/SlashMenu.style.ts

fix https://github.com/mashcard/mashcard/issues/160
https://github.com/mashcard/mashcard/issues/165
https://github.com/mashcard/mashcard/issues/72

fix: font colot btn default color/ cornel problem/ trash list

---

packages/editor/__snapshots__/components/blockViews/BlockActions/__tests__/BlockActionButton.text.tsx.snap
packages/editor/__snapshots__/components/blockViews/BlockActions/__tests__/BlockActions.test.tsx.snap
packages/editor/__snapshots__/components/blockViews/EmbedView/__tests__/EmbedView.test.tsx.snap
packages/editor/__snapshots__/editors/documentEditor/__tests__/documentEditor.test.tsx.snap
packages/editor/src/components/blockViews/BlockActions/BlockActionButton/BlockActionButton.tsx
packages/editor/src/components/blockViews/BlockActions/BlockActions.tsx

fix https://github.com/pleisto/corp/issues/1837

fix(ediotr): fix popover placement

---

packages/editor/src/components/blockViews/EmbedView/embedViews/ImageView/ImageView.style.ts
packages/editor/src/components/blockViews/EmbedView/embedViews/ImageView/ImageView.tsx

fix(editor): aligns toolbar correctly due to image alignment

---

.github/workflows/unit_test.yml
apps/server-monolith/Gemfile
apps/server-monolith/Gemfile.lock
apps/server-monolith/spec/spec_helper.rb

feat(coverage): add backend-unit to codecov

---

.yarn/patches/@tiptap-react-npm-2.0.0-beta.114-77e1d9a671.patch
apps/client-web/src/entrypoints/application.tsx
package.json
yarn.lock

Add a patch to fix the bug until @tiptap fixes it.
ref: https://github.com/ueberdosis/tiptap/pull/2985
fix #345

fix: @tiptap react render bug in React 18

---

apps/client-web/src/docs_legacy/pages/DocumentContentPage.tsx
packages/editor/src/editors/documentEditor/documentEditor.tsx

fix(document): fix history panel when opening a link with historyId

---

apps/client-web/src/docs_legacy/common/components/TrashTable/Trash.style.ts
apps/client-web/src/docs_legacy/pages/components/DocumentTitle/DocumentTitle.style.ts
packages/editor/__snapshots__/components/blockViews/EmbedView/__tests__/EmbedView.test.tsx.snap
packages/editor/__snapshots__/components/blockViews/EmbedView/__tests__/embedViews/PreviewView/WebsiteDocument.test.tsx.snap
packages/editor/__snapshots__/components/ui/Toolbar/__tests__/Toolbar.test.tsx.snap
packages/editor/src/components/extensionViews/BubbleMenu/useBubbleMenuItems/useNodeGroup.tsx
packages/editor/src/components/ui/Toolbar/Toolbar.tsx
packages/editor/src/components/ui/Toolbar/styles/index.style.ts

fix https://github.com/mashcard/mashcard/issues/141
fix https://github.com/mashcard/mashcard/issues/34
fix https://github.com/mashcard/mashcard/issues/165

fix bubble menu/multi titile

---

apps/server-monolith/config/locales/pwa.en-US.yml
packages/editor/src/components/blockViews/Spreadsheet/SpreadsheetBlockView.tsx

#180 spreadsheet title/column error message
#295 spreadsheet must have at least one row

feat(spreadsheet)

---

apps/server-monolith/Gemfile.lock
packages/editor/src/components/blockViews/Spreadsheet/SpreadsheetBlockView.tsx

fix(spreadsheet): check spreadsheet title on blur

---

apps/server-monolith/package.json
package.json
packages/design-system/package.json
packages/dev-support/package.json
yarn.lock

This is an [auto-created](https://github.com/mashcard/mashcard/blob/main/.github/workflows/dependency_updater.yml) PR to upgrade dependencies.

chore(deps): upgrade dependencies

---

apps/server-monolith/package.json
package.json
packages/design-system/package.json
packages/dev-support/package.json
yarn.lock

Revert "chore(deps): upgrade dependencies"

---

packages/editor/src/components/blockViews/EmbedView/EmbedView.tsx
packages/editor/src/components/blockViews/EmbedView/__tests__/embedViews/PreviewView/WebsiteDocument.test.tsx
packages/editor/src/components/blockViews/EmbedView/embedTypes/Link/useLinkValue.ts
packages/editor/src/components/blockViews/EmbedView/embedViews/CardView/CardView.tsx
packages/editor/src/components/blockViews/EmbedView/embedViews/PreviewView/DocumentFooter.tsx
packages/editor/src/components/blockViews/EmbedView/embedViews/PreviewView/PdftronDocument/PdftronDocument.tsx
packages/editor/src/components/blockViews/EmbedView/embedViews/PreviewView/PreviewView.tsx
packages/editor/src/components/blockViews/EmbedView/embedViews/PreviewView/WebsiteDocument.tsx

fix(editor): fix embed block editing url will lose url metadata

---

apps/server-monolith/Gemfile.lock
packages/editor/__snapshots__/components/ui/Toolbar/__tests__/Toolbar.test.tsx.snap
packages/editor/src/components/extensionViews/BubbleMenu/useBubbleMenuItems/useNodeGroup.tsx
packages/editor/src/components/ui/Toolbar/MenuSubMenuItem.tsx

https://github.com/mashcard/mashcard/issues/34

fix(ediotr): fix submenu icon width

---

packages/legacy-editor/src/components/editorViews/ExplorerMenu/ExplorerMenu.style.ts

fix https://github.com/mashcard/mashcard/issues/301
FYI: https://developer.mozilla.org/en-US/docs/Web/CSS/overscroll-behavior

fix(client): fix explorer-menu scroll limit problem

---

packages/legacy-editor/src/editors/documentEditor/documentEditor.tsx

fix(editor): disable auto focus

---

packages/legacy-editor/__snapshots__/extensions/blocks/horizontalRule/__tests__/horizontalRule.test.tsx.snap
packages/legacy-editor/src/extensions/blocks/horizontalRule/horizontalRule.ts

fix(editor): make horizontal-rule draggable

---

packages/formula/src/context/context.ts
packages/formula/src/context/variable.ts
packages/formula/src/type/index.ts
packages/legacy-editor/src/components/blockViews/Spreadsheet/SpreadsheetBlockView.tsx
packages/legacy-editor/src/components/blockViews/Spreadsheet/SpreadsheetCell.tsx
packages/legacy-editor/src/components/blockViews/Spreadsheet/useFormulaSpreadsheet.ts
packages/legacy-editor/src/components/blockViews/Spreadsheet/useSpreadsheet.ts

Keep correct formulaId when rerender.

fix(formula): keep correct formula id

---

packages/legacy-editor/src/components/extensionViews/BubbleMenu/useBubbleMenuItems/useNodeGroup.tsx

fix list item turns into other node type failed problem.
fix #258

fix(editor): lift list item before toggle node type

---

packages/legacy-editor/src/components/blockViews/Spreadsheet/SpreadsheetBlockView.tsx
packages/legacy-editor/src/components/blockViews/Spreadsheet/SpreadsheetCell.tsx
packages/legacy-editor/src/components/blockViews/Spreadsheet/useFormulaSpreadsheet.ts

fix(formula): spreadsheet rerender parse error

---

packages/legacy-editor/src/extensions/blocks/horizontalRule/inputRule.ts
packages/legacy-editor/src/extensions/blocks/listItem/listItem.ts
packages/legacy-editor/src/extensions/blocks/taskItem/taskItem.ts

fix #353 
1. always create new line after insert horizontal-rule
2. allows only paragraph and sub-list inside list 
ref: https://github.com/mashcard/mashcard/discussions/308

Fix horizontal creation

---

packages/editor/src/NodePortal/NodePortalContainer.tsx
packages/editor/src/NodePortal/__tests__/NodePortalContainer.test.tsx
packages/editor/src/NodePortal/useNodePortals.ts
packages/legacy-editor/src/tiptapRefactor/Editor.ts
packages/legacy-editor/src/tiptapRefactor/EditorContent.tsx
packages/legacy-editor/src/tiptapRefactor/ReactRenderer.tsx

Use `createPortal` magic third argument `key` to make portal rendering efficient.

refactor(legacy-editor): improve node view portal rendering

---

packages/formula/src/grammar/dependency.ts
packages/formula/src/tests/feature/spreadsheetVariable.ts
packages/legacy-editor/src/components/blockViews/Spreadsheet/SpreadsheetCell.tsx

* fix #453
fix another deadlock bug.

fix(formula): another deadlock bug

---

apps/client-web/src/routes/$domain/$docId/_shared/DocumentTopBar/PathBreadcrumb/PathBreadcrumb.tsx

fix(document): title on breadcrumb

---

apps/client-web/src/MashcardGraphQL.ts
apps/client-web/src/routes/$domain/$docId/_shared/DocumentEditor/TrashPrompt/TrashPrompt.tsx
apps/client-web/src/routes/$domain/$docId/_shared/graphql.ts

- fix restore button for children document
- remove close button from trash prompt

fix(trash): fix trash prompt

---

packages/legacy-editor/__snapshots__/components/blockViews/TocView/__tests__/TocView.test.tsx.snap
packages/legacy-editor/src/components/blockViews/TocView/TocNodePanel.tsx

https://github.com/mashcard/mashcard/issues/262

fix(ediotr): adjust toc size

---

apps/client-web/src/routes/$domain.settings/_shared/SwitchSettingPod.tsx
apps/server-monolith/config/locales/pwa.en-US.yml
packages/formula/src/context/context.ts
packages/formula/src/context/variable.ts
packages/formula/src/grammar/core.ts
packages/formula/src/type/index.ts

fix: pod setting i18n

---

packages/formula/src/tests/feature/basic/basicType.ts
packages/legacy-editor/__snapshots__/components/blockViews/FormulaView/__tests__/formulaType.test.tsx.snap
packages/legacy-editor/__snapshots__/components/ui/Formula/AutocompleteList/__tests__/AutocompleteList.test.tsx.snap
packages/legacy-editor/__snapshots__/components/ui/Formula/__tests__/FormulaDisplay.test.tsx.snap
packages/legacy-editor/__snapshots__/components/ui/Formula/__tests__/FormulaResult.test.tsx.snap
packages/legacy-editor/__snapshots__/components/ui/Formula/__tests__/FormulaValue.test.tsx.snap
packages/legacy-editor/src/components/ui/Formula/FormulaValue.tsx
packages/legacy-editor/src/components/ui/Formula/__tests__/FormulaValue.test.tsx
packages/legacy-editor/src/components/ui/Formula/color.tsx

feat(formula): update color system

---

apps/server-monolith/app/controllers/storages_controller.rb
apps/server-monolith/app/graphql/mutations/create_direct_upload.rb

fix: ActiveStorage download url, fix #300

---

apps/server-monolith/app/graphql/mutations/create_direct_upload.rb

fix: fallback other MIME_TYPE

---

packages/legacy-editor/__snapshots__/components/editorViews/Discussion/__tests__/Comment.test.tsx.snap
packages/legacy-editor/__snapshots__/components/editorViews/Discussion/__tests__/Conversation/Conversation.test.tsx.snap
packages/legacy-editor/__snapshots__/editors/commentEditor/__tests__/commentEditor.test.tsx.snap
packages/legacy-editor/src/components/editorViews/Discussion/Comment.tsx
packages/legacy-editor/src/components/editorViews/Discussion/Conversation/useConversationEffects.ts
packages/legacy-editor/src/editors/commentEditor/commentEditor.style.ts
packages/legacy-editor/src/editors/commentEditor/commentEditor.tsx
packages/legacy-editor/src/editors/commentEditor/useCommentEditor.ts
packages/legacy-editor/src/extensions/extensions/comment/comment.ts
packages/legacy-editor/src/extensions/extensions/comment/index.ts
packages/legacy-editor/src/extensions/extensions/comment/meta.ts
packages/legacy-editor/src/extensions/extensions/index.ts

resolve #326
Press 'Enter' to send the comment.
Press 'Shift-Enter' to add a new line.

Fix comment editor

---

apps/server-monolith/app/graphql/mutations/blocks/sync_batch.rb
apps/server-monolith/app/graphql/resolvers/block_info.rb
apps/server-monolith/app/graphql/resolvers/block_new.rb
apps/server-monolith/spec/graphql/mutations/blocks/sync_batch_spec.rb
apps/server-monolith/spec/graphql/resolvers/block_info_spec.rb

fix: remember last position #243

---

packages/legacy-editor/src/editors/commentEditor/commentEditor.tsx
packages/legacy-editor/src/editors/commentEditor/useCommentEditor.ts
packages/legacy-editor/src/extensions/extensions/comment/index.ts

fix(editor): makes pressing Enter to send comment correctly

---

packages/legacy-editor/src/components/blockViews/BlockActions/useBasicActionOptions.tsx

Fix clipboard firefox
